# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_inputdialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 649)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 400, 361, 41))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(40, 30, 711, 441))
        self.listWidget.setObjectName("listWidget")
        self.btnBrowse = QtWidgets.QPushButton(Dialog)
        self.btnBrowse.setGeometry(QtCore.QRect(540, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnBrowse.setFont(font)
        self.btnBrowse.setObjectName("btnBrowse")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setGeometry(QtCore.QRect(-370, 40, 27, 22))
        self.toolButton.setObjectName("toolButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(80, 290, 141, 91))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 60, 95, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 40, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(80, 120, 611, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 180, 231, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 151, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 40, 151, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 60, 201, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 180, 281, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 40, 221, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 60, 221, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 221, 20))
        self.checkBox.setObjectName("checkBox")
        self.listWidget.raise_()
        self.buttonBox.raise_()
        self.btnBrowse.raise_()
        self.toolButton.raise_()
        self.groupBox.raise_()
        self.lineEdit.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnBrowse.setText(_translate("Dialog", "Выберите папку"))
        self.groupBox.setTitle(_translate("Dialog", "Archieve formats"))
        self.radioButton.setText(_translate("Dialog", "7zip"))
        self.radioButton_3.setText(_translate("Dialog", "tar.gz"))
        self.radioButton_2.setText(_translate("Dialog", "ZIP"))
        self.groupBox_2.setTitle(_translate("Dialog", "Update mode"))
        self.radioButton_4.setText(_translate("Dialog", "Add and replace files"))
        self.radioButton_5.setText(_translate("Dialog", "Add and update files"))
        self.radioButton_6.setText(_translate("Dialog", "Synchronize archieve contents"))
        self.groupBox_3.setTitle(_translate("Dialog", "Archiving options"))
        self.checkBox_2.setText(_translate("Dialog", "Test archieved files"))
        self.checkBox_3.setText(_translate("Dialog", "Lock archieve"))
        self.checkBox.setText(_translate("Dialog", "Delete files after archiving"))

